import type { Metadata } from "next";
import { Geist, Geist_Mono, Assistant, Fjalla_One } from "next/font/google"; // Assistant যোগ করা হয়েছে
import "./globals.css";
import Navbar from "@/app/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Assistant ফন্ট কনফিগারেশন
const assistant = Assistant({
  variable: "--font-assistant", // এই নামটা CSS-এ ব্যবহার হবে
  subsets: ["latin"],
  display: "swap",
});

const fjalla = Fjalla_One({
  weight: "400", // Fjalla One এর সাধারণত একটিই ওয়েট থাকে
  variable: "--font-fjalla", 
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Fabrilife Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        /* বডিতে ${assistant.variable} যোগ করা হয়েছে */
        className={`${geistSans.variable} ${geistMono.variable} ${assistant.variable} ${fjalla.variable} font-assistant antialiased`}
        suppressHydrationWarning={true}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}